### ISSUE TITLE
Add Docker repository link to source repository

### ISSUE THREAD

**Issue by johannrichard** [cismet/docker-rotated-delete#2]
The Docker Hub lets you link your own repositories to other source repositories. Updates of the source repository and builds will trigger a rebuild of your own repository, too, keeping the image and the installed software updated. 

Maybe you can add this to the Docker repository related to this project, too?

I think you should normally find the setting at https://hub.docker.com/r/cismet/rotated-delete/~/settings/automated-builds/

**Comment by helllth** [comment]
Thanks for the remark. That has already been done. I added a Docker-Hub Badge to the `Readme.md` to emphasize that.
